config/routes.rb
Rails.application.routes.draw do
  patch 'links/:id' => 'links#update', as: :links
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'dashboard', to: 'dashboard#index'
  get 'appearance', to: 'dashboard#appearance'
  root 'dashboard#index'

  # Allows us to use user_path(user) to get the URL for a user's profile page
  get ':id', to: 'dashboard#show', as: :user
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user, only: [:show]
  def index
    @should_render_navbar = true
  end

  def appearance
    @should_render_navbar = true
  end

  def show
    redirect_to dashboard_path if @user.nil?

    @links = @user.links.where.not(url: '', title: '')
  end

  private

  def set_user
    # localhost:3000/1

    @user = User.friendly.find(params[:id])
  rescue StandardError
    @user = nil
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/appearance.html.erb
<div class="container">
    <h1 style="text-align:center;">Appearance</h1>
    <%= simple_form_for(current_user, 
        url: registration_path(current_user), 
        html: { method: :put },
        data: {turbo: false }) do |f| %>
        <div class="row">
            <div class="col-6">
                <div class="row mt-5">
                    <div class="col-6">
                        <%= image_tag(current_user.avatar, class:"avatar-image") if current_user.avatar.attached? %>
                    </div>
                    <div class="col-6 mt-5">
                        <%= f.input :avatar, required: false, label: false %>
                    </div>

                </div>

                <div class="row mt-5">
                    <div class="col-6 no-padding-col">
                        <%= f.input :full_name, placeholder: "Your full name...", label: false, class: "form-control", required: false %>
                    </div>
                    <div class="col-6 no-padding-col">
                        <div class="input-group mb-3">
                            <span class="input-group-text">@</span>
                            <%= f.input :username, placeholder: "Your username...", label: false, class: "form-control", required: true %>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col no-padding-col">
                        <div class="input-group row">
                            <%= f.input :body, placeholder: "About you...", label: false, class:"form-control", required: false%>
                        </div>
                    </div>
                </div>

                <div class="col-4 no-padding-col">
                    <%= f.submit "Update Account", class:"btn btn-primary" %>
                </div>
            </div>
            <div class="col-6">
            </div>
        </div>
    <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="container">
<div class="row">
    <div class="col-3"></div>
        <div class="col-6 " >
            <h1 class="text-center">Link Manager</h1>
            <% current_user.links.each do |link| %>
                <%= simple_form_for(link, url: links_url(link)) do |f| %>
                    <%= f.input :title, placeholder: "Title", label: false, class:"form-control" %>
                    <%= f.input :url, placeholder: "URL", label: false, class:"form-control" %>
                    <%= f.submit "Update Link", class:"btn btn-primary me-auto" %>
                <% end %>
            <% end %>

        </div>
    <div class="col-3"></div>
</div>
</div>

app/views/dashboard/show.html.erb
<div class="profile-page">
    <div class="container">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-10">
                <div class="row mt-5">
                    <div class="col-12 d-flex justify-content-center">
                        <%= image_tag(@user.avatar, class:"avatar-image") if @user.avatar.attached? %>
                    </div>
                    <div class="col-12 d-flex justify-content-center">
                        <h2 class="white-font"><%= @user.full_name %></h2>
                    </div>
                    <div class="col-12 d-flex justify-content-center">
                        <p class="white-font"><%= @user.body %></p>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
            <div class="row">
                <div class="col-1"></div>
                    <div class="col-10 ">
                        <% @links.each do |link| %>
                        <div class="row">
                            <div class="col-12 d-flex justify-content-center">
                                <%= link_to link.url, target: "_blank", class:"linkable btn btn-secondary" do %>
                                    <span class="linkable-span"><%= link.title %></span>
                                <% end %>
                            </div>
                        </div>
                        <% end %>
                    </div>
                <div class="col-1"></div>
        </div>
    </div>
</div>